### ISSUE TITLE
Change 'insert' text when checked

### ISSUE THREAD

**Issue by hmaesta** [drgullin/icheck#155]
Hello.
Is there a way to change the 'insert' text when input is checked?

Something like...

``` js
$('input').iCheck({
   default_insert: 'Press me!',
   checked_insert: 'Oh yeah!'
});
```

![qqq](https://cloud.githubusercontent.com/assets/741969/2576370/9f56832a-b96d-11e3-97cc-e69d62fd9bc4.png)

Thank you.

**Comment by hmaesta** [comment]
Until now, my solution is with CSS.

``` css
.iradio:before {
    content: "Press me!"
}
.iradio.checked:before {
    content: "Oh yeah!"
}
```

(And **no** 'insert' in iCheck function)
