### ISSUE TITLE
Aligning the radio buttons

### ISSUE THREAD

**Issue by Holdsie** [drgullin/icheck#51]
How do I align the radio buttons to the center of a table "td" element? Thanks.

**Comment by drgullin** [comment]
You may try something like this:

``` css
.icheckbox,
.iradio {
  float: none;
  display: block;
  margin: 0 auto;
}
```
